services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fpl_ultimate
      POSTGRES_USER: ${FPL_DB_USER:-fpl_user}
      POSTGRES_PASSWORD: ${FPL_DB_PASSWORD:-fpl_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
