# API Configuration
football.api.host=https://v3.football.api-sports.io/
football.api.username=${FOOTBALL_API_USERNAME}
football.api.password=${FOOTBALL_API_PASSWORD}
football.api.key=${FOOTBALL_API_KEY}

# Mock everything by default - check each environment's properties file
# to see what is enabled in that environment
mock.football.api=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

server.port=5000