mock.football.api=false

# DataSource settings for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fpl_ultimate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=creation_api
spring.datasource.password=<your-password>

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect