# Database configuration
fpl.database.username=${FPL_DB_USER:fpl_db_user}
fpl.database.password=${FPL_DB_PASSWORD:fpl_db_password}

# API Configuration
football.api.host=${FOOTBALL_API_HOST}
football.api.username=${FOOTBALL_API_USERNAME}
football.api.password=${FOOTBALL_API_PASSWORD}
football.api.key=${FOOTBALL_API_KEY}

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console